//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingCastleCloud.Rules {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleDescription() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PingCastleCloud.Rules.RuleDescription", typeof(RuleDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The purpose of this rule is to check that ADConnect has no know vulnerabilities.
        /// </summary>
        internal static string ADConnectVersion_Description {
            get {
                return ResourceManager.GetString("ADConnectVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version: {0}.
        /// </summary>
        internal static string ADConnectVersion_Detail {
            get {
                return ResourceManager.GetString("ADConnectVersion_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://dirteam.com/sander/2021/08/10/two-new-azure-ad-connect-versions-were-released-to-prevent-mitm-attacks-towards-domain-controllers-cve-2021-36949/
        ///https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-36949.
        /// </summary>
        internal static string ADConnectVersion_Documentation {
            get {
                return ResourceManager.GetString("ADConnectVersion_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The ADConnect version is known to be vulnerable.
        /// </summary>
        internal static string ADConnectVersion_Rationale {
            get {
                return ResourceManager.GetString("ADConnectVersion_Rationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ADConnectVersion_ReportLocation {
            get {
                return ResourceManager.GetString("ADConnectVersion_ReportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to update ADConnect.
        ///    .
        /// </summary>
        internal static string ADConnectVersion_Solution {
            get {
                return ResourceManager.GetString("ADConnectVersion_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Azure AD Connect v1.6.11.3 is is security update release of Azure AD Connect v1.x. This release addresses the vulnerability as documented in CVE-2021-36949.
        ///	Azure AD Connect v2.0.8.0 is a security update release of Azure AD Connect v2.x. This release addresses the vulnerability as documented in CVE-2021-36949..
        /// </summary>
        internal static string ADConnectVersion_TechnicalExplanation {
            get {
                return ResourceManager.GetString("ADConnectVersion_TechnicalExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check if ADConnect is known to be vulnerable.
        /// </summary>
        internal static string ADConnectVersion_Title {
            get {
                return ResourceManager.GetString("ADConnectVersion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The purpose of this rule is to check that ADConnect is not running version 1.
        /// </summary>
        internal static string ADConnectVersion1_Description {
            get {
                return ResourceManager.GetString("ADConnectVersion1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version: {0}.
        /// </summary>
        internal static string ADConnectVersion1_Detail {
            get {
                return ResourceManager.GetString("ADConnectVersion1_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://azure.microsoft.com/en-us/updates/action-required-upgrade-to-the-latest-version-of-azure-ad-connect-before-31-august-2022/
        ///https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-upgrade-previous-version.
        /// </summary>
        internal static string ADConnectVersion1_Documentation {
            get {
                return ResourceManager.GetString("ADConnectVersion1_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The ADConnect version is on the branch 1.X.X.X.
        /// </summary>
        internal static string ADConnectVersion1_Rationale {
            get {
                return ResourceManager.GetString("ADConnectVersion1_Rationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ADConnectVersion1_ReportLocation {
            get {
                return ResourceManager.GetString("ADConnectVersion1_ReportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to update ADConnect.
        ///    .
        /// </summary>
        internal static string ADConnectVersion1_Solution {
            get {
                return ResourceManager.GetString("ADConnectVersion1_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Azure AD Connect v1.X.X.X is obsolete starting August, 31th 2022. It is recommended to use version 2.X.X.X..
        /// </summary>
        internal static string ADConnectVersion1_TechnicalExplanation {
            get {
                return ResourceManager.GetString("ADConnectVersion1_TechnicalExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check if ADConnect is on the branch 1.X.X.X.
        /// </summary>
        internal static string ADConnectVersion1_Title {
            get {
                return ResourceManager.GetString("ADConnectVersion1_Title", resourceCulture);
            }
        }
    }
}
